#pragma once
#include <string>
#include <vector>
#include <fstream>
#include <sstream>
#include <cstdint>
#include <cstring>

struct ModStateFile {
    bool flyEnabled = false;
    float flySpeed = 1.0f;
    bool speedEnabled = false;
    float speedMultiplier = 2.0f;
    bool noclipEnabled = false;
    bool invisibleEnabled = false;
    bool longArmsEnabled = false;
    float armLength = 1.5f;
    bool teleportEnabled = false;
    bool grabAllEnabled = false;
    bool itemGunEnabled = false;
    int itemGunIndex = 0;
    bool tagGunEnabled = false;
    bool kickGunEnabled = false;
    bool instaKillGun = false;
    bool teleportGunEnabled = false;
    bool spazEnabled = false;
    bool freezeEnabled = false;
    bool goopSpamEnabled = false;
    bool triggerCloneSpawn = false;
    bool rigFollowEnabled = false;
    bool orbitClonesEnabled = false;
    bool cloneLineMode = false;
    bool godMode = false;
    bool invincible = false;
    bool noclip = false;
    bool invisible = false;
    bool fullbright = false;
    bool rainbowSelf = false;
    bool rainbowAll = false;
    bool playerESP = false;
    bool rpcKillAll = false;
    bool rpcReviveAll = false;
    bool rpcTPAllToMe = false;
    bool rpcStunAll = false;
    bool rpcLaunchAll = false;
    bool instaKillAll = false;
    bool pissMod = false;
    bool coverAllGoopfish = false;
    bool orbitPlayers = false;
    bool pullAll = false;
    bool floatAll = false;
    bool gravityAll = false;
    bool tpAllToVoid = false;
    bool kickAll = false;
    bool kickGun = false;
    bool pushGun = false;
    bool flingGun = false;
    bool colorGun = false;
    bool explosionGun = false;
    bool launchAllGun = false;
    bool orbitGun = false;
    bool ragdollAllGun = false;
    bool spawnGun = false;
    int spawnItemIndex = 0;
    bool spawnMobGun = false;
    int mobIndex = 0;
    bool noGravityHeld = false;
    bool addGravityHeld = false;
    bool scaleHeldUp = false;
    bool scaleHeldDown = false;
    bool yeetGun = false;
    bool launcherGun = false;
    bool crateGun = false;
    bool stashDupe = false;
    bool backpackDupe = false;
    bool speedBuff = false;
    bool strengthBuff = false;
    bool stealthBuff = false;
    bool allBuffs = false;
    bool buffAllPlayers = false;
    bool jetpackInfFuel = false;
    bool infAmmoAll = false;
    bool superJump = false;
    bool maxJumpHeight = false;
    bool shopUnlock = false;
    bool unlockAll = false;
    bool openAllDoors = false;
    bool closeAllDoors = false;
    bool popAllBalloons = false;
    bool toggleBoomboxes = false;
    bool activateTeleporters = false;
    bool thunderStrike = false;
    bool arenaStartSpam = false;
    bool arenaNoDespawn = false;
    bool infiniteHoverpad = false;
    bool arenaItemBurst = false;
    bool giveLotsOfNuts = false;
    bool giveLotsOfCC = false;
    bool giveResearchPoints = false;
    bool unlockAllItems = false;
    bool sellingSpasm = false;
    bool flushAllToilets = false;
    bool toiletSpam = false;
    bool toiletPaperBurst = false;
    bool dupeMachineMax = false;
    bool rocketFist = false;
    bool boomspearFist = false;
    bool eggFist = false;
    bool bombArrowFist = false;
    bool flareFist = false;
    bool bigHands = false;
    bool normalSize = false;
    bool rgbMenu = false;
    bool handPlatforms = false;
    bool triggerFly = false;
    bool superSmoothFly = false;
    bool infSprint = false;
    bool noRecoil = false;
    bool noWeaponCooldown = false;
    bool infFarts = false;
    bool blueNameTags = false;
    bool wlFly = false;
    bool wlRocket = false;
    bool wlFlare = false;
    bool wlCar = false;
    bool wlCrate = false;
    bool wlSuitcase = false;
    bool wlBomb = false;
    bool wlEgg = false;
    bool wlBalloon = false;
    bool spawnConfetti = false;
    bool nightAlarm = false;
    bool sellAllItems = false;
    bool spawnSellingMachine = false;
    bool spawnDupeMachine = false;
    bool deleteAllItems = false;
    bool deleteAllMobs = false;
    bool deleteAllPrefabs = false;
    bool customPrefabOrbit = false;
    bool christmasOrbit = false;
    bool sellingMachineOrbit = false;
    bool carOrbit = false;
    bool prefabGun = false;
    int prefabIndex = 0;
    bool spawnAllWeapons = false;
    bool killAllMobs = false;
    bool autoKickAll = false;
    bool tpAllGun = false;
    bool kickAllGrip = false;
    bool tpAllToMe = false;
    bool tpMeToRandom = false;
    bool spamBuffAll = false;
    bool buffSpam = false;
    bool spawnItems = false;
    bool bringAllItems = false;
    bool spawnMob = false;
    bool deleteHeldItem = false;
    bool handDuper = false;
    bool selectedLauncherItem = false;
    int launcherItemIndex = 0;
    bool timebombLauncher = false;
    bool pelicanCaseLauncher = false;
    bool rareCardLauncher = false;
    bool rocketLauncher = false;
    bool userKick = false;
    bool userTP = false;
    bool userPull = false;
    bool wlSpazRainbow = false;
    bool wlDisintegrate = false;
    bool wlSpeedBuff = false;
    bool wlTornado = false;
    bool wlBlackHole = false;
    bool wlFlash = false;
    bool wlTeleport = false;
    bool wlKick = false;
    bool wlFreeze = false;
    bool wlItemStorm = false;
    bool wlFirework = false;
    bool wlCage = false;
    bool wlGiveaway = false;
    bool wlFlyPress = false;
    bool wlRocketPress = false;
    bool rainItems = false;
    bool launchAll = false;
    bool explodeAll = false;
    bool dragAll = false;
    bool floatFreezeAll = false;
    bool wlSpeedBuffSelf = false;
    bool wlStealthBuffSelf = false;
    bool wlAllBuffsSelf = false;
    bool spamRainbowAll = false;
    bool blueprintAbuse = false;
    bool noSpend = false;
    bool ownAllCosmetics = false;
    bool vendingBypass = false;
    bool patchEverything = false;
    bool devMode = false;
    bool tpToLake = false;
    bool tpToMoon = false;
    bool tpToSewers = false;
    bool tpToSpawn = false;
    bool tpToWaterTower = false;
    bool tpToSkybox = false;
    bool tpToVoid = false;
    int selectedPlayer = 0;
    int numPlayers = 0;
};

inline ModStateFile& GetModStateFile() {
    static ModStateFile state;
    return state;
}

inline bool ReadModState(ModStateFile& s, const char* path) {
    std::ifstream f(path);
    if (!f.is_open()) return false;
    std::string content((std::istreambuf_iterator<char>(f)), std::istreambuf_iterator<char>());

    auto getBool = [&](const char* key) -> bool {
        size_t pos = content.find(key);
        if (pos == std::string::npos) return false;
        pos = content.find(':', pos);
        if (pos == std::string::npos) return false;
        pos++;
        while (pos < content.size() && content[pos] == ' ') pos++;
        return content.substr(pos, 4) == "true";
    };

    auto getInt = [&](const char* key) -> int {
        size_t pos = content.find(key);
        if (pos == std::string::npos) return 0;
        pos = content.find(':', pos);
        if (pos == std::string::npos) return 0;
        pos++;
        while (pos < content.size() && content[pos] == ' ') pos++;
        int val = 0;
        while (pos < content.size() && content[pos] >= '0' && content[pos] <= '9') {
            val = val * 10 + (content[pos] - '0');
            pos++;
        }
        return val;
    };

    auto getFloat = [&](const char* key) -> float {
        size_t pos = content.find(key);
        if (pos == std::string::npos) return 0.0f;
        pos = content.find(':', pos);
        if (pos == std::string::npos) return 0.0f;
        pos++;
        while (pos < content.size() && content[pos] == ' ') pos++;
        return (float)atof(content.c_str() + pos);
    };

    s.flyEnabled = getBool("flyEnabled");
    s.flySpeed = getFloat("flySpeed");
    s.speedEnabled = getBool("speedEnabled");
    s.speedMultiplier = getFloat("speedMultiplier");
    s.noclipEnabled = getBool("noclipEnabled");
    s.invisibleEnabled = getBool("invisibleEnabled");
    s.longArmsEnabled = getBool("longArmsEnabled");
    s.armLength = getFloat("armLength");
    s.teleportEnabled = getBool("teleportEnabled");
    s.grabAllEnabled = getBool("grabAllEnabled");
    s.itemGunEnabled = getBool("itemGunEnabled");
    s.itemGunIndex = getInt("itemGunIndex");
    s.tagGunEnabled = getBool("tagGunEnabled");
    s.kickGunEnabled = getBool("kickGunEnabled");
    s.instaKillGun = getBool("instaKillGun");
    s.teleportGunEnabled = getBool("teleportGunEnabled");
    s.spazEnabled = getBool("spazEnabled");
    s.freezeEnabled = getBool("freezeEnabled");
    s.goopSpamEnabled = getBool("goopSpamEnabled");
    s.triggerCloneSpawn = getBool("triggerCloneSpawn");
    s.rigFollowEnabled = getBool("rigFollowEnabled");
    s.orbitClonesEnabled = getBool("orbitClonesEnabled");
    s.cloneLineMode = getBool("cloneLineMode");
    s.godMode = getBool("godMode");
    s.invincible = getBool("invincible");
    s.noclip = getBool("noclip");
    s.invisible = getBool("invisible");
    s.fullbright = getBool("fullbright");
    s.rainbowSelf = getBool("rainbowSelf");
    s.rainbowAll = getBool("rainbowAll");
    s.playerESP = getBool("playerESP");
    s.rpcKillAll = getBool("rpcKillAll");
    s.rpcReviveAll = getBool("rpcReviveAll");
    s.rpcTPAllToMe = getBool("rpcTPAllToMe");
    s.rpcStunAll = getBool("rpcStunAll");
    s.rpcLaunchAll = getBool("rpcLaunchAll");
    s.instaKillAll = getBool("instaKillAll");
    s.pissMod = getBool("pissMod");
    s.coverAllGoopfish = getBool("coverAllGoopfish");
    s.orbitPlayers = getBool("orbitPlayers");
    s.pullAll = getBool("pullAll");
    s.floatAll = getBool("floatAll");
    s.gravityAll = getBool("gravityAll");
    s.tpAllToVoid = getBool("tpAllToVoid");
    s.kickAll = getBool("kickAll");
    s.kickGun = getBool("kickGun");
    s.pushGun = getBool("pushGun");
    s.flingGun = getBool("flingGun");
    s.colorGun = getBool("colorGun");
    s.explosionGun = getBool("explosionGun");
    s.launchAllGun = getBool("launchAllGun");
    s.orbitGun = getBool("orbitGun");
    s.ragdollAllGun = getBool("ragdollAllGun");
    s.spawnGun = getBool("spawnGun");
    s.spawnItemIndex = getInt("spawnItemIndex");
    s.spawnMobGun = getBool("spawnMobGun");
    s.mobIndex = getInt("mobIndex");
    s.noGravityHeld = getBool("noGravityHeld");
    s.addGravityHeld = getBool("addGravityHeld");
    s.scaleHeldUp = getBool("scaleHeldUp");
    s.scaleHeldDown = getBool("scaleHeldDown");
    s.yeetGun = getBool("yeetGun");
    s.launcherGun = getBool("launcherGun");
    s.crateGun = getBool("crateGun");
    s.stashDupe = getBool("stashDupe");
    s.backpackDupe = getBool("backpackDupe");
    s.speedBuff = getBool("speedBuff");
    s.strengthBuff = getBool("strengthBuff");
    s.stealthBuff = getBool("stealthBuff");
    s.allBuffs = getBool("allBuffs");
    s.buffAllPlayers = getBool("buffAllPlayers");
    s.jetpackInfFuel = getBool("jetpackInfFuel");
    s.infAmmoAll = getBool("infAmmoAll");
    s.superJump = getBool("superJump");
    s.maxJumpHeight = getBool("maxJumpHeight");
    s.shopUnlock = getBool("shopUnlock");
    s.unlockAll = getBool("unlockAll");
    s.openAllDoors = getBool("openAllDoors");
    s.closeAllDoors = getBool("closeAllDoors");
    s.popAllBalloons = getBool("popAllBalloons");
    s.toggleBoomboxes = getBool("toggleBoomboxes");
    s.activateTeleporters = getBool("activateTeleporters");
    s.thunderStrike = getBool("thunderStrike");
    s.arenaStartSpam = getBool("arenaStartSpam");
    s.arenaNoDespawn = getBool("arenaNoDespawn");
    s.infiniteHoverpad = getBool("infiniteHoverpad");
    s.arenaItemBurst = getBool("arenaItemBurst");
    s.giveLotsOfNuts = getBool("giveLotsOfNuts");
    s.giveLotsOfCC = getBool("giveLotsOfCC");
    s.giveResearchPoints = getBool("giveResearchPoints");
    s.unlockAllItems = getBool("unlockAllItems");
    s.sellingSpasm = getBool("sellingSpasm");
    s.flushAllToilets = getBool("flushAllToilets");
    s.toiletSpam = getBool("toiletSpam");
    s.toiletPaperBurst = getBool("toiletPaperBurst");
    s.dupeMachineMax = getBool("dupeMachineMax");
    s.rocketFist = getBool("rocketFist");
    s.boomspearFist = getBool("boomspearFist");
    s.eggFist = getBool("eggFist");
    s.bombArrowFist = getBool("bombArrowFist");
    s.flareFist = getBool("flareFist");
    s.bigHands = getBool("bigHands");
    s.normalSize = getBool("normalSize");
    s.rgbMenu = getBool("rgbMenu");
    s.handPlatforms = getBool("handPlatforms");
    s.triggerFly = getBool("triggerFly");
    s.superSmoothFly = getBool("superSmoothFly");
    s.infSprint = getBool("infSprint");
    s.noRecoil = getBool("noRecoil");
    s.noWeaponCooldown = getBool("noWeaponCooldown");
    s.infFarts = getBool("infFarts");
    s.blueNameTags = getBool("blueNameTags");
    s.wlFly = getBool("wlFly");
    s.wlRocket = getBool("wlRocket");
    s.wlFlare = getBool("wlFlare");
    s.wlCar = getBool("wlCar");
    s.wlCrate = getBool("wlCrate");
    s.wlSuitcase = getBool("wlSuitcase");
    s.wlBomb = getBool("wlBomb");
    s.wlEgg = getBool("wlEgg");
    s.wlBalloon = getBool("wlBalloon");
    s.spawnConfetti = getBool("spawnConfetti");
    s.nightAlarm = getBool("nightAlarm");
    s.sellAllItems = getBool("sellAllItems");
    s.spawnSellingMachine = getBool("spawnSellingMachine");
    s.spawnDupeMachine = getBool("spawnDupeMachine");
    s.deleteAllItems = getBool("deleteAllItems");
    s.deleteAllMobs = getBool("deleteAllMobs");
    s.deleteAllPrefabs = getBool("deleteAllPrefabs");
    s.customPrefabOrbit = getBool("customPrefabOrbit");
    s.christmasOrbit = getBool("christmasOrbit");
    s.sellingMachineOrbit = getBool("sellingMachineOrbit");
    s.carOrbit = getBool("carOrbit");
    s.prefabGun = getBool("prefabGun");
    s.prefabIndex = getInt("prefabIndex");
    s.spawnAllWeapons = getBool("spawnAllWeapons");
    s.killAllMobs = getBool("killAllMobs");
    s.autoKickAll = getBool("autoKickAll");
    s.tpAllGun = getBool("tpAllGun");
    s.kickAllGrip = getBool("kickAllGrip");
    s.tpAllToMe = getBool("tpAllToMe");
    s.tpMeToRandom = getBool("tpMeToRandom");
    s.spamBuffAll = getBool("spamBuffAll");
    s.buffSpam = getBool("buffSpam");
    s.selectedPlayer = getInt("selectedPlayer");
    s.userKick = getBool("userKick");
    s.userTP = getBool("userTP");
    s.userPull = getBool("userPull");

    return true;
}
