#pragma once
// AUTO-GENERATED by dumper.py - Do not edit
// Generated: 2026-06-25T09:39:02.739Z
#include <cstdint>

namespace offsets {

    // === Field Offsets (from Il2Cpp runtime) ===
    // These are the actual runtime offsets, not static analysis
    // Usage: read<T>(classInstance + offsets::ClassName::FieldName)

    // === Method Addresses ===
    // Runtime method pointers - use these to call/hook methods

}  // namespace offsets
